### ISSUE TITLE
Docs: install instructions are wrong

### ISSUE THREAD

**Issue by singingwolfboy** [eropple/taskbotjs#6]
[On the installation docs page](https://github.com/eropple/taskbotjs/wiki/User%27s-Guide-02%3A00-Installation), the instructions say to install, among other things, `@taskbotjs/server`. However, [that package doesn't exist on NPM](https://registry.npmjs.org/@taskbotjs/server). It appears that the correct package name is [`@taskbotjs/service`](https://www.npmjs.com/package/@taskbotjs/service).

Could you update this doc page, please? Getting a mysterious error on install is not a good way to get started with a new software package. :(

**Comment by eropple** [comment]
Ack. Good catch; thank you for going through those. I renamed it because it seemed a little odd to call it "the server" when it was instantiating your stuff, but, hm. Now I'm rethinking.

Fixing now.
